name: KPMain
version: '1.0'
main: org.newplugin.kpmain.KPMain
api-version: '1.20'
commands:
  removetokens:
    description: Removes tokens from player
  tokenbal:
    description: Shows how many tokens the player has
  tokens:
    description: Opens the gui
  givetokens:
    description: Gives the player tokens
    usage: /tokensgive <USER> <AMOUNT>\

permissions:
  kpmain.givetokens:
    description: lets the player give tokens
    default: op
  kpmain.page:
    default: false
  kpmain.squire:
    default: false
  kpmain.knight:
    default: false
  kpmain.paladin:
    default: false
  kpmain.captain:
    default: false
  kpmain.lieutenant:
    default: false
  kpmain.commander:
    default: false
  kpmain.general:
    default: false
  kpmain.marshal:
    default: false
  kpmain.champion:
    default: false